site_name: KATIAU

nav:
  - K.A.T.I.A.U ⚡: index.md
  - Como documentar: como_documentar.md
  - Projeto Conceitual: Documentacao
  - Atas: Atas\Reuniões
  
theme: readthedocs
plugins:
  - search
  - include_dir_to_nav
